### ISSUE TITLE
Does not show in sidebar flow-editor

### ISSUE THREAD

**Issue by arnodeclercq** [athombv/com.google.chromecast#14]
Can't use this app because it doesn't show up in the sidebar for the flow-editor.
App version: v0.11.3
Homey version: 0.10.3

**Comment by matjaz** [comment]
It's a driver. First you need to add device.

**Comment by arnodeclercq** [comment]
Ok, that makes sense. I didn't think of that.
Thanks for the reply!

**Comment by WeeJeWel** [comment]
Do you have a device paired?
