### ISSUE TITLE
App from Athom B.V. *Verified Developer* in the store appears to be from Emile when installed.

### ISSUE THREAD

**Issue by Dijker** [athombv/com.google.chromecast#15]
Looked at the App after installing: 

![image](https://cloud.githubusercontent.com/assets/12412734/20295502/99aa2a3a-ab05-11e6-8c83-185145249de9.png)

Expected Athom B.V. * there as it is promoted that way in the Appstore!

**Comment by BasKiers** [comment]
This issue was fixed, thank you for reporting!
