### ISSUE TITLE
Cast to Android TV 

### ISSUE THREAD

**Issue by djeskoswe** [athombv/com.google.chromecast#18]
After update to 2.0.3 the app wont find my cast android TV ( Sony) ,  did work before update.

fw .1.0.3

Thanks

**Comment by bvdbos** [comment]
@djeskoswe Did you re-pair the tv and didn't the app find it during pairing? Or did you try to cast a video to an already existing device?

**Comment by djeskoswe** [comment]
Re-pair but no device found,  rebooted tv and homey

**Comment by bvdbos** [comment]
https://forum.athom.com/discussion/2427/chromecast-app#latest

**Comment by BasKiers** [comment]
Hi, 

I think I know why the app is unable to find it. Do you know how to sideload an app? If so I can give you a version which will work and you can help me add it to the app in the app store.

**Comment by djeskoswe** [comment]
Sure,  send apk link

**Comment by BasKiers** [comment]
I just committed a new version with some logging and disabled the check for device id. If you could run the app and just wait until the log message `found device with txtMD ...` appears and copy paste that message here I can add the id to the app. (project link https://github.com/athombv/com.google.chromecast)

**Comment by Radiotechniman** [comment]
found device with txtMD BRAVIA 4K GB

**Comment by BasKiers** [comment]
Hmm, I had hoped it would give a more generic name instead of the tv name since this would mean I need to add all custom chromecast devices manually. Could you also post the full data which should be printed after the txtMD name?

**Comment by Radiotechniman** [comment]
sure
`found device with txtMD BRAVIA 4K GB { addresses: [ '192.168.1.121' ],
  query: [],
  type: 
   [ { name: 'googlecast',
       protocol: 'tcp',
       subtypes: [],
       description: 'Google Chromecast' } ],
  txt: 
   [ 'id=47b57a99b649123262ec6b35f62f5b10',
     'rm=D122C1125796A589',
     've=05',
     'md=BRAVIA 4K GB',
     'ic=/setup/icon.png',
     'fn=Bravia',
     'ca=2053',
     'st=0',
     'bs=FFFFFFFFFFFF',
     'rs=' ],
  port: 8009,
  fullname: 'BRAVIA-4K-GB-47b57a99b649123262ec6b35f62f5b10._googlecast._tcp.local',
  host: '47b57a99-b649-1232-62ec-6b35f62f5b10.local',
  interfaceIndex: 1,
  networkInterface: 'pseudo multicast',
  txtObj: 
   { id: '47b57a99b649123262ec6b35f62f5b10',
     rm: 'D122C1125796A589',
     ve: '05',
     md: 'BRAVIA 4K GB',
     ic: '/setup/icon.png',
     fn: 'Bravia',
     ca: '2053',
     st: '0',
     bs: 'FFFFFFFFFFFF',
     rs: '' } }
[log][chromecast] Found Bravia @ 192.168.1.121
found device with txtMD BRAVIA 4K GB { addresses: [ '192.168.1.121' ],
  query: [],
  type: 
   [ { name: 'googlecast',
       protocol: 'tcp',
       subtypes: [],
       description: 'Google Chromecast' } ],
  txt: 
   [ 'id=47b57a99b649123262ec6b35f62f5b10',
     'rm=D122C1125796A589',
     've=05',
     'md=BRAVIA 4K GB',
     'ic=/setup/icon.png',
     'fn=Bravia',
     'ca=2053',
     'st=0',
     'bs=FFFFFFFFFFFF',
     'rs=' ],
  port: 8009,
  fullname: 'BRAVIA-4K-GB-47b57a99b649123262ec6b35f62f5b10._googlecast._tcp.local',
  host: '47b57a99-b649-1232-62ec-6b35f62f5b10.local',
  interfaceIndex: 1,
  networkInterface: 'pseudo multicast',
  txtObj: 
   { id: '47b57a99b649123262ec6b35f62f5b10',
     rm: 'D122C1125796A589',
     ve: '05',
     md: 'BRAVIA 4K GB',
     ic: '/setup/icon.png',
     fn: 'Bravia',
     ca: '2053',
     st: '0',
     bs: 'FFFFFFFFFFFF',
     rs: '' } }
[log][chromecast_audio] Found Bravia @ 192.168.1.121`

**Comment by djeskoswe** [comment]
found device with txtMD BRAVIA 4K 2015

**Comment by WeeJeWel** [comment]
@baskiers we might need an additional strategy, e.g. check for a few cast-specific fields (good read: https://github.com/jloutsenhizer/CR-Cast/wiki/Chromecast-Implementation-Documentation-WIPl) 

Unfortunately we can't rely on the domain broadcast alone because I've seem the Hue Bridge respond as well :')

**Comment by BasKiers** [comment]
@WeeJeWel indeed, this part in the device object looks promising: `type: [ { name: 'googlecast', protocol: 'tcp', subtypes: [], description: 'Google Chromecast' } ]`

**Comment by WeeJeWel** [comment]
Indeed! Maybe add sentry logging for all results with a txtObj?

**Comment by BasKiers** [comment]
Could you confirm the version that I just pushed finds your tv? If so I push the changes to the appstore.

**Comment by djeskoswe** [comment]
i can find the device but app crash 

Stack trace:

TypeError: Cannot read property 'replace' of undefined
at DriverChromecast._onMdnsDevice (/lib/Driver.js:84:30)
at emitOne (events.js:82:20)
at App.emit (events.js:169:7)
at App._onBrowserUpdate (/app.js:29:8)
at emitOne (events.js:77:13)
at emit (events.js:169:7)
at internal.onMessage (/node_modules/mdns-js/lib/browser.js:109:12)
at emitThree (events.js:97:13)
at emit (events.js:175:7)
at Socket.<anonymous> (/node_modules/mdns-js/lib/networking.js:142:10)
at emitTwo (events.js:87:13)
at Socket.emit (events.js:172:7)
at UDP.onMessage (dgram.js:480:8)

Exit code: 1

**Comment by BasKiers** [comment]
Are you sure you downloaded the latest version of the project when that crash occured? If so I did push another check to be certain that crash cannot happen. Could you try again?

**Comment by djeskoswe** [comment]
no crash now but this 

![2016-12-17 13_08_58-flow - homey](https://cloud.githubusercontent.com/assets/17300121/21286648/0c432bce-c45a-11e6-97db-4424f43d5907.png)

**Comment by BasKiers** [comment]
This is expected. The cast video URL should work with this : http://media.dumpert.nl/mp3/27856e31_Tiroler_Rosi.mp3.mp3

**Comment by djeskoswe** [comment]
works , nice sound :)

**Comment by BasKiers** [comment]
Ok, I will add the changes to the app in the appstore and close this issue. Please open a new issue when you experience other problems. Thank you for helping!
