### ISSUE TITLE
Cast to ChromeAudio enabled speakers 

### ISSUE THREAD

**Issue by Radiotechniman** [athombv/com.google.chromecast#19]
I have several of these (LG Music Flow) but it does not work, the app states there are no (new) devices found, likely same issue as with the (sony) androidtv

**Comment by BasKiers** [comment]
Hi, I am currently debugging the exact same issue (but for the chromecast enabled tv's) in issue #18. Could you do the same as I asked over there (run the app from command line and wait for the `found device with txtMD ...` log message to comment it here)?

**Comment by Radiotechniman** [comment]
found device with txtMD Music Flow H3
found device with txtMD Music Flow H5

**Comment by Radiotechniman** [comment]
not sure if this is an issue, the below is my NAS

`found device with txtMD undefined { addresses: [ '192.168.1.19' ],
  query: [],
  txt: [ 'model=path=/', '' ],
  type: 
   [ { name: 'ftp',
       protocol: 'tcp',
       subtypes: [],
       description: 'FTP File Transfer' },
     { name: 'smb',
       protocol: 'tcp',
       subtypes: [],
       description: 'Microsoft Windows Network' } ],
  port: 445,
  fullname: 'JUPITER._smb._tcp.local',
  host: 'JUPITER.local',
  interfaceIndex: 1,
  networkInterface: 'pseudo multicast',
  txtObj: { model: 'path', '': undefined } }
TypeError: Cannot read property 'replace' of undefined
    at DriverChromecast._onMdnsDevice (/lib/Driver.js:84:30)
    at emitOne (events.js:82:20)
    at App.emit (events.js:169:7)
    at App._onBrowserUpdate (/app.js:29:8)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at internal.onMessage (/node_modules/mdns-js/lib/browser.js:109:12)
    at emitThree (events.js:97:13)
    at emit (events.js:175:7)
    at Socket.<anonymous> (/node_modules/mdns-js/lib/networking.js:142:10)
    at emitTwo (events.js:87:13)
    at Socket.emit (events.js:172:7)
    at UDP.onMessage (dgram.js:480:8)`

**Comment by BasKiers** [comment]
Yes the error occurs because I removed the filter for only chromecast devices and it could be the app cannot handle a device that is not a chromecast. Could you print the full logs from the Music Flow devices (including the object behind it)?

**Comment by BasKiers** [comment]
I've updated the app in the appstore to version 2.0.5 which now should support third party chromecast devices after some testing in issue #18. Looking at your logs this fix should also apply for your chromecast audio devices. Could you update to the newest version in the appstore and confirm that it works? Thanks for helping resolve this issue!
