### ISSUE TITLE
Chromecast app does not find any Chromecast device

### ISSUE THREAD

**Issue by Muyz** [athombv/com.google.chromecast#2]
Have 2 Chromecasts of latest generation. Installed Google Chromecast v0.10.0 on Homey with SW 0.8.17. Added Chromecast to a flow, but no devices are found.

**Comment by matjaz** [comment]
Library for discovering Chromecast devices uses SSDP and MDNS protocols.
Can you please try debug locally using node? https://github.com/athombv/com.google.chromecast/blob/710e13a9b824ede2cc1d59a25cb9d00a1c07c0ed/drivers/chromecast/driver.js#L52

**Comment by Muyz** [comment]
Issue can be closed; mea culpa and thanks for your support!
