### ISSUE TITLE
casting youtube needs reboot after every request

### ISSUE THREAD

**Issue by mauritsivs** [athombv/com.google.chromecast#21]
Since the V2 update i am not able to cast anything to the chromecast anymore.
after re-adding the chromecast to my devices, i am only able to send a video once. after that i need to reboot homey or disable/enable the chromecast app. 
when i test a simple flow to cast a YouTube video all that happens is a rotating icon shows up on the cast-card. 
sending commands like stop and pause do get recognized and get a green V in the test.

**Comment by bvdbos** [comment]
Are you on 1.0.3 of Homey or 1.0.5?

**Comment by mauritsivs** [comment]
im on 1.0.3

**Comment by BasKiers** [comment]
Hi,

I've heard multiple people report this bug but I am unable to find what causes this thus far. For now you can use the chromecast app by calling the "stop" card before sending another video but I am investigating how I can solve this.

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not?

**Comment by jeroenvollenbrock** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible, or it has been fixed in a newer version.

Please let me know if you still encounter this issue with the [latest stable version](https://firmware.athom.com/).

Thank you!
