### ISSUE TITLE
Load failed Radio Stations

### ISSUE THREAD

**Issue by gajdur** [athombv/com.google.chromecast#23]
Trying the new app with radio stations capabilities.

Every try is ending into "load failed" message into chromecast. PTP done, still the same error. Tried with multiple stations, same. Log 742C36DB39.

**Comment by kikkerX10** [comment]
it is still not working. Still the same message code"load failed"

**Comment by gajdur** [comment]
News here?

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not?

**Comment by jeroenvollenbrock** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible, or it has been fixed in a newer version.

Please let me know if you still encounter this issue with the [latest stable version](https://firmware.athom.com/).

Thank you!
