### ISSUE TITLE
Casting hidden youtube video's does not work

### ISSUE THREAD

**Issue by jeroenvano** [athombv/com.google.chromecast#25]
Hi,

I tried to cast a hidden YouTube video what did not work.
If you enter the URL into the field it changes correctly into the video name and you can save the flow.
Executing the flow results into an error after 30sec or so.

Casting hidden youtube playlists does work so this is a work around until this is fixed.

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2685
