### ISSUE TITLE
Playing a second video fails

### ISSUE THREAD

**Issue by netactivenl** [athombv/com.google.chromecast#3]
There seems to be an issue playing a second video through the same Chromecast device. The very first video (after starting the Chromecast app in debug) plays fine. When I later start a second video the app fails to do so and outputs an exception on the debug console:

D:_GitHub\com.google.chromecast>athom project --run
? Select active Homey: Homey @ 192.168.xx.yy:80
Archiving...
Uploading to 192.168.xx.yy:80...
Running `com.google.chromecast`...
Debugging...
Woonkamer []
device null
videoUrl  https://www.youtube.com/watch?v=xxxxxxxxx
Woonkamer [ { domain: null,
    _events: {},
    config: { name: 'Woonkamer', addresses: [Object] },
    host: '192.168.xx.yy',
    playing: false },
  { domain: null,
    _events: {},
    config: { name: 'Slaapkamer', addresses: [Object] },
    host: '192.168.xx.yy',
    playing: false } ]
device { domain: null,
  _events: {},
  config: { name: 'Woonkamer', addresses: [ '192.168.xx.yy' ] },
  host: '192.168.xx.yy',
  playing: false }
videoUrl  https://www.youtube.com/watch?v=zzzzzzzzzz
Playing on your chromecast
TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at process.target._send (child_process.js:479:23)
    at process.target.send (child_process.js:416:12)
    at Object.Homey.client.emit (/opt/homey-client/system/types/manager/apps/boo
tstrap/homey-app/helpers/client.js:1:300)
    at log (/opt/homey-client/system/types/manager/apps/bootstrap/homey-app/help
ers/log.js:1:270)
    at Object.Homey.log (/opt/homey-client/system/types/manager/apps/bootstrap/h
omey-app/helpers/log.js:1:319)
    at Object.exports.playVideo (/drivers/chromecast/driver.js:27:8)
    at Object.onFlowActionCastVideo (/app.js:46:4)
    at Object.emit (events.js:118:17)
    at /opt/homey-client/system/types/manager/apps/bootstrap/homey-app/manager/f
low.js:1:188

**Comment by matjaz** [comment]
Error `Converting circular structure to JSON` is triggered because you're outputting some circular objects (`media`?)
That's not related to casting problems.

As I can see your devices are discovered. As I can see on first play back no devices were found (`device null`), so the callback should be called with an error. Can you confirm this?

**Comment by BasKiers** [comment]
The app has been rewritten and all crashes should be fixed. Please open a new issue if you experience problems.
