### ISSUE TITLE
Chromecast app keeps crashing after not being used

### ISSUE THREAD

**Issue by dmpcc** [athombv/com.google.chromecast#32]
Hi,

Let me first provide some context:
I am running version 3.0.1 of the app on Homey Firmware Version: 1.3.0-rc.7.
There 6 chrome-cast speakers in a castgroup. The castgroup is added as a device in homey.

I use basically three flows:
1. A voice activated flow to homey to start casting of a radio station
2. A voice activated flow to stop the cast.
3. A IFTTT flow linked to my alarm to start casting a radio station

Everything works perfect most of the time. But after a while (a night sleep etc.) not using the app sometimes is crashed. And when I want to start a flow to cast the radio station (alarm or voice) nothing will happen.
When I log in into homey. I can see the device as blurred and the flows 'broken'. In the settings menu going to Apps the Chromecast app got a red triangle with the balloon in saying it crashed. I have to restart the app to make it work again.

Can you please look into this?

I cant find any logs, but I you provide instructions on how to extract them I will.

**Comment by hnijveen** [comment]
Same issue with the app as described above: see also: https://github.com/athombv/homey/issues/1622 for the log.

**Comment by dmpcc** [comment]
Here is the crashlog: 2A28294978

**Comment by jeroenvollenbrock** [comment]
I'm closing this issue as it is supposedly fixed in the latest update. If the problem persists, please let me know.
