### ISSUE TITLE
Feature Request If Chromecast is casting then....

### ISSUE THREAD

**Issue by fuzzbdn** [athombv/com.google.chromecast#34]
Hi i'm wondering if it's possible to get a flow card for "When" chromecast plays something.
Example 
If i cast spotify to my chromecast audio then turn on amplifier and set the right source.

**Comment by mruiter** [comment]
Yes , would love this to. Now my TV goes on with a stream by command.
But since i run different NOS streams i dont now in advance for how long.
Can easly do a auto turn of but i need something like trigger if running or a main trigger when stream stops or starts for example

**Comment by jaimevisser** [comment]
Really a must have feature for having a movie mode when you use a chromecast for everything! Plex notify works somewhat but not for Netflix and Youtube. Additionally "When chromecast stops playing" and a token on the device "playing" and/or "casting" would be awesome!

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2682
