### ISSUE TITLE
Pause don't work

### ISSUE THREAD

**Issue by Bozo29** [athombv/com.google.chromecast#35]
"Pauzeer", "Speel af", "Volgende"en "Vorige" flowcharts don't work in a flow, Homey don't regonize these commands (flowchards). Mute, stop en cast radiostation etc.  works perfect.

**Comment by BasKiers** [comment]
Hi,

Pause, play, next and previous only work when playback is started from Homey. Could you confirm that you are trying to use these flow cards when the chromecast is playing something that Homey initiated?

Regards,
Bas

**Comment by jeroenvollenbrock** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible, or it has been fixed in a newer version.

Please open a new issue if you still encounter this issue with the [latest Homey version](https://firmware.athom.com/).

Thank you!
