### ISSUE TITLE
Feature request: Pauze/Resume any content on chromecast

### ISSUE THREAD

**Issue by jjtbsomhorst** [athombv/com.google.chromecast#36]
It is possible with the chromecast to let it be controlled by any android device in the same network. This is something that we have currently enabled and therefore when we are watching a movie we can pauze it on any device we have near us. 

It would be nice if we can have the same functionality for the Homey app so we can ask homey to pauze / resume the movie we are currently watching using netflix.

**Comment by rogerjak** [comment]
+1
Mostly casting from Android (Netflix) or Videostream (local files) and I'd like flows like:
"When incoming call and Chromecast playing then pause"

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2681
