### ISSUE TITLE
Request flowcard: "When google home is listening."

### ISSUE THREAD

**Issue by pjmpessers** [athombv/com.google.chromecast#45]
Hello.

I have more a request then a issue . Is there a possibility to have a flowcard for google home when listening. When my TV or receiver is on and playing music, google home has trouble picking up my request. When there is a flowcard: When google home is listening" i could make a flow muting my TV and/or receiver. And when there would be a flowcard: "Google home stops listening." would also be great. But that is not necessary. I could make it unmute after 10 seconds.

Thanks.

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2679
