### ISSUE TITLE
Chromecast ultra support

### ISSUE THREAD

**Issue by LyoshaDovolen** [athombv/com.google.chromecast#46]
Please add  Chromecast ultra support

**Comment by Rocodamelshe** [comment]
Can i add that my Chromecast Ultra is working like it should? Have the 2 stripe thingie on it but casting radiostations is working so besides the other issue Ultra is working with my Homey.

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2678
