### ISSUE TITLE
Nothing is being casted to my Chromecasts

### ISSUE THREAD

**Issue by lucasochfredrik** [athombv/com.google.chromecast#47]
Hi!

Seems like a basic main flow use case I'm describing but I can't get it to work for some reason so I was hoping someone could provide some assistant. I have several issues in this area but lets take an easy to describe use case. 

I have a Google mini connected with the Homey app and I'm able to control volume through Homey so I know it is detected.
When I enter the "Music" tab in Homey and try to select a different speaker other than the internal jack or "Homey" which is stated in the lower right corner nothing happens. I click, get the menu where I see my chromecast. Once I click on it, I get a "ding" sound from the chromecast but still "Homey" is selected as the active speaker. Same goes for flow when trying to select a different active speaker.

What am I doing wrong? This use cases is advertised on the Athom webpage so it should work, right?

I should point out that when I try to cast any radio, youtube or webpage to the chromecast it either gives a timeout error or some other Load error. In this case I use the chromecast speaker device in the flow. I have also tried this on my chromecast audio and have the same problem. 

Appriciate any type of help!

**Comment by dickklein** [comment]
Same problem here.

Casting a radiostation by a flow works fine, but music over my chromecast audio won't work.

**Comment by lucasochfredrik** [comment]
True, the radio casting works for me as well for some station, not the one I wanted though

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2677
