### ISSUE TITLE
Chromecast crashes when sending a picture since 4.0.2.

### ISSUE THREAD

**Issue by 2benl** [athombv/com.google.chromecast#50]
Since Chromecast 4.0.2 the app crashes when a picture is being send.
4.0.1 didn't have this problem.
Crashlog: 477795f6-2a3c-42fb-9ba1-84bcbaecb685

**Comment by 2benl** [comment]
Another crashlog: 05d5b925-5a1a-426b-8e36-640e5eed95fb

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2674
