### ISSUE TITLE
App installs an Philips Hue device

### ISSUE THREAD

**Issue by freemann** [athombv/com.google.chromecast#6]
After installing the ChromeCast App, I started the add device wizard and it found a device called "Philips HUE". I just installed it because it maybe had just mixedup some names, but after installing the App really installed a device connected to the HUE ip.

![screenshot - 25-4-2016 20_41_57](https://cloud.githubusercontent.com/assets/601053/14794903/5d364ce8-0b26-11e6-948f-baa317aed042.png)

**Comment by freemann** [comment]
Tried a reinstall, but same issue.

**Comment by matjaz** [comment]
related to #12

**Comment by BasKiers** [comment]
The app has been rewritten and the hue bridge has been filtered from the device list. Please open a new issue if you experience problems.

**Comment by freemann** [comment]
Thanx for the quick fix!
